# Generated by Django 5.1.7 on 2025-03-09 13:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    # replaces = [('main_app', '0001_initial'), ('main_app', '0002_product_created_on_product_last_edited_on')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('supplier', models.CharField(blank=True, max_length=150, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now)),
                ('last_edited_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
